### ISSUE TITLE
How do I use an existing world & Add a mod?

### ISSUE THREAD

**Issue by SecretUnicorn** [JonasBonno/docker-ftb-revelation#5] opened 2021-02-14 04:13 UTC
Question is in the title? How do I use an existing world with this docker image? In addition to that I would like to add a mod and remove another. How do I archive that ?

Thanks in advance!

**Comment by IrishWolf** [comment] 2021-02-14 17:17
I think your questions  were already answered in one of the closed tickets.

> The only option is to skip the data container with:
> 
> _docker run --tty=true --interactive=true --detach=true --name=[name of your container] -v /[path on host]:/minecraft/world --publish=[port on your host]:25565 jonasbonno/ftb-revelation_
> 
> This will cause the server container to use a local folder for the world-data, but still you cannot add/modify the server mods from SFTP, you need SSH/console on host to do this.
>
> _Source: https://github.com/JonasBonno/docker-ftb-revelation/issues/3#issuecomment-626034605_

I think with this you should be able to use your existing world.

---

> If you want to change things in the server container you could use the following to access it:
> 
> Access container:
> docker exec -it [name of your container] bash
>
> Inside the container you could install Linux packets or download/modify additional files, but it cannot be done from SFTP, you need SSH/console on host to do this.
>
> _Source: https://github.com/JonasBonno/docker-ftb-revelation/issues/3#issuecomment-625763269_

**Comment by JonasBonno** [comment] 2021-02-16 21:07
Duplicate of #3

**Closed as completed by JonasBonno** 2021-02-16 21:07 UTC
Labels: duplicate
